version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
        - run:
            name: Build
            command: 'ls'
  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
       - run:
          name: Deploy
          command: 'aws s3 sync ${source}/ s3://${bucket} --region us-east-2 --exclude "*" --include "*.js"'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy